version: "2"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: pikai123
      POSTGRES_DB: dbms
  app:
    image: my-node-app
    ports:
      - 13000:8000
